# Generated by Django 4.1.3 on 2022-11-23 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_livros_delete_books'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books',
        ),
        migrations.RenameField(
            model_name='livros',
            old_name='nomeLivro',
            new_name='livro',
        ),
    ]
